# Colors (Nord)
colors:
  # Default colors
  primary:
    background: '0x2E3440'
    foreground: '0xD8DEE9'

  # Normal colors
  normal:
    black:   '0x3B4252'
    red:     '0xBF616A'
    green:   '0xA3BE8C'
    yellow:  '0xEBCB8B'
    blue:    '0x81A1C1'
    magenta: '0xB48EAD'
    cyan:    '0x88C0D0'
    white:   '0xE5E9F0'

  # Bright colors
  bright:
    black:   '0x4C566A'
    red:     '0xBF616A'
    green:   '0xA3BE8C'
    yellow:  '0xEBCB8B'
    blue:    '0x81A1C1'
    magenta: '0xB48EAD'
    cyan:    '0x8FBCBB'
    white:   '0xECEFF4'
    
    # Font config:
font:
    normal:
        family: JetbrainsMono Nerd Font
        style: Regular
 
    bold:
        family: JetbrainsMono Nerd Font
        style: Bold
 
    italic:
        family: JetbrainsMono Nerd Font
        style: Italic
 
    bold_italic:
        family: JetbrainsMono Nerd Font
        style: Bold Italic
    size: 10.5

key_bindings:
  -  { key: F11, action:
ToggleFullScreen}


########################## WINDOW ##########################
window:
   dimensions:
     columns: 85
     lines: 25
   decorations: full
   padding:
      x: 5
      y: 5
   dynamic_padding: false
   opacity: 1
   dynamic_title: true
   resize_increments: false
########################## CURSOR ##########################   
cursor:
  style:
    shape: Block
    blinking: On
  blink_interval: 750
  blink_timeout: 0
############################################################
mouse:
    hide_when_typing: true
